
qserver:
  port: 8899

# This is config channal for bank Acquirer
bank:
  vib:
    host: localhost
    port: 5504
  tcb:
    host: localhost
    port: 5505
  vcb:
    host: localhost
    port: 5506

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpos3
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
